# Generated by Django 3.2.8 on 2021-12-19 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_date_of_birth_authormodel_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20211218_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
