# Generated by Django 3.2.8 on 2022-01-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='seen_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
