# Generated by Django 3.2.8 on 2022-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220104_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='seen_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
