# Generated by Django 3.2.8 on 2021-12-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentfiles',
            options={'ordering': ['file']},
        ),
        migrations.AlterModelOptions(
            name='authormodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genremodel',
            options={'ordering': ['title']},
        ),
    ]
