# Generated by Django 3.2.8 on 2021-12-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211216_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
