# Generated by Django 3.2.8 on 2021-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_authormodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
