# Generated by Django 3.2.8 on 2021-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_authormodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('m', 'male'), ('f', 'female')], null=True),
        ),
    ]
