# Generated by Django 3.2.8 on 2021-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_authormodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='male', max_length=10),
        ),
    ]
