# Generated by Django 3.2.8 on 2021-12-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211216_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='production_year',
            field=models.DateField(null=True),
        ),
    ]
