# Generated by Django 3.2.8 on 2021-12-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bookmodel_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
