# Generated by Django 3.2.8 on 2021-12-17 12:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20211216_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='genremodel',
            name='image',
            field=models.ImageField(null=True, upload_to=base.models.image_path),
        ),
        migrations.AlterField(
            model_name='attachmentfiles',
            name='file',
            field=models.FileField(upload_to='attach_files/%y-%m-%d_%H:%M'),
        ),
    ]
