# Generated by Django 3.2.8 on 2021-12-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211217_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
