# Generated by Django 3.2.8 on 2021-12-17 15:31

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_bookmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='image',
            field=models.ImageField(null=True, upload_to=base.models.image_path),
        ),
    ]
