# Generated by Django 3.2.8 on 2021-12-17 17:00

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_authormodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=base.models.image_path),
        ),
    ]
