# Generated by Django 3.2.8 on 2021-12-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_bookmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
    ]
