# Generated by Django 3.2.8 on 2022-01-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_bookmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='genremodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
