# Generated by Django 3.2.8 on 2022-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220102_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
